# Customer Segmentation Configuration
app:
  name: "Customer Segmentation Analysis"
  version: "1.0.0"
  description: "A comprehensive web application for customer segmentation using ML clustering"

clustering:
  default_features:
    - "Annual Income (k$)"
    - "Spending Score (1-100)"
  
  kmeans:
    default_clusters: 5
    max_clusters: 15
    random_state: 42
    n_init: 10
  
  dbscan:
    default_eps: 0.5
    default_min_samples: 5
    eps_range: [0.1, 2.0]
    min_samples_range: [2, 20]

data:
  sample_size: 200
  random_seed: 42
  
  expected_columns:
    - "CustomerID"
    - "Gender"
    - "Age"
    - "Annual Income (k$)"
    - "Spending Score (1-100)"

visualization:
  colors:
    primary: "#1f77b4"
    secondary: "#ff7f0e"
    success: "#2ca02c"
    warning: "#ff7f0e"
    error: "#d62728"
  
  plot_settings:
    height: 400
    width: 600
    dpi: 100

streamlit:
  page_config:
    page_title: "Customer Segmentation Analysis"
    page_icon: "🛍️"
    layout: "wide"
    initial_sidebar_state: "expanded"
